# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor [[[

[flavor]
dark  = ""
light = ""

# : ]]]


# : App [[[

[app]
overall = {}

# : ]]]


# : Manager [[[

[mgr]
cwd = { fg = "{{colors.on_surface.default.hex}}" }

# Find
find_keyword = { fg = "{{colors.error.default.hex}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{colors.error.default.hex}}", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 20.0}}", bg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 20.0}}" }
marker_cut = { fg = "{{colors.tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
marker_marked = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_selected = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Count
count_copied = { fg = "{{colors.on_tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
count_cut = { fg = "{{colors.on_tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
count_selected = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Border
border_symbol = " "
border_style  = { fg = "{{colors.surface_tint.default.hex}}" }

# : ]]]


# : Tabs [[[

[tabs]
active = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
inactive  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : ]]]


# : Mode [[[

[mode]
normal_main = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
normal_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Select mode
select_main = { bg = "{{colors.secondary.default.hex}}", fg = "{{colors.on_secondary.default.hex}}", bold = true }
select_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Unset mode
unset_main = { bg = "{{colors.tertiary.default.hex}}", fg = "{{colors.on_tertiary.default.hex}}", bold = true }
unset_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# : ]]]


# : Indicator of hovered file [[[

[indicator]
parent  = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", reversed = true }
current = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
preview = { underline = true }
padding = { open = "", close = "" }

# : ]]]


# : Status bar [[[

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "{{colors.primary_fixed.default.hex | auto_lightness: 30.0}}" }
perm_type = { fg = "{{colors.secondary.default.hex | auto_lightness: 30.0}}" }
perm_read = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 30.0}}" }
perm_write = { fg = "{{colors.tertiary.default.hex | auto_lightness: 30.0}}" }
perm_exec = { fg = "{{colors.error.default.hex | auto_lightness: 30.0}}" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }
progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "{{colors.surface_bright.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}" }
rest = { fg = "{{colors.on_primary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
separator = " ▶ "
separator_style = { fg = "{{colors.on_surface.default.hex}}" }

# : ]]]


# : Confirmation [[[

[confirm]
border = { fg = "{{colors.primary.default.hex}}" }
title = { fg = "{{colors.on_surface.default.hex}}" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : ]]]


# : Spotter [[[

[spot]
border = { fg = "{{colors.primary.default.hex}}" }
title = { fg = "{{colors.on_surface.default.hex}}" }

# Table
tbl_col  = { fg = "{{colors.on_surface.default.hex}}" }
tbl_cell = { fg = "{{colors.on_surface.default.hex}}", reversed = true }

# : ]]]


# : Notification [[[

[notify]
title_info = { fg = "{{colors.tertiary.default.hex}}" }
title_warn = { fg = "{{colors.primary.default.hex}}" }
title_error = { fg = "{{colors.error.default.hex}}" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : ]]]


# : Picker [[[

[pick]
border = { fg = "{{colors.primary.default.hex}}" }
active = { fg = "{{colors.tertiary.default.hex}}", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "{{colors.primary.default.hex}}" }
title    = {}
value = { fg = "{{colors.on_surface.default.hex}}" }
selected = { reversed = true }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.on_primary.default.hex}}" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "{{colors.primary.default.hex}}" }
title = {}
hovered = { fg = "{{colors.tertiary_fixed.default.hex}}", underline = true }

# : ]]]


# : Help menu [[[

[help]
on = { fg = "{{colors.on_surface.default.hex}}" }
run = { fg = "{{colors.on_surface.default.hex}}" }
desc    = {}
hovered = { reversed = true, bold = true }
footer = { fg = "{{colors.on_secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "{{colors.error_container.default.hex}}" },
    { name = "*", is = "exec", fg = "{{colors.on_error_container.default.hex}}" },

    # Fallback
    { name = "*", fg = "{{colors.on_surface.default.hex}}" },
    { name = "*/", fg = "{{colors.surface_tint.default.hex}}" },
]

# : ]]]
