# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = "rose-pine-moon"

# : }}}


# : Manager {{{

[mgr]
# Border
border_symbol = " "
border_style  = { fg = "gray" }

# : }}}


# : Tabs {{{

[tabs]
# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Indicator of hovered file {{{

[indicator]
parent  = { reversed = true }
current = { reversed = true, bold = true }
preview = { underline = true }
padding = { open = "█", close = "█" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "yellow" },
	# Media
	{ mime = "{audio,video}/*", fg = "magenta" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "cyan" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "gray" },
	# Special file
	{ url = "*", is = "orphan", bg = "red" },
	{ url = "*", is = "exec"  , fg = "green" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "red" },
	{ url = "*/", is = "dummy", bg = "red" },
	# Fallback
	{ url = "*/", fg = "blue" }
]

# : }}}


